format:
	npx tsx ./format-package-lock-cmake.ts

update:
	npx tsx ./update-package-lock-cmake.ts
	npx tsx ./format-package-lock-cmake.ts

pnpm-install:
	pnpm install

pnpm-update:
	pnpm update

pnpm-audit:
	pnpm audit
